micronaut:
  application:
    name: telegaBot
    default-charset: UTF-8
  server:
    port: 7373
liquibase:
  datasource:
    default:
      change-log: classpath\:db/liquibase-changelog.xml
netty:
  default:
    allocator:
      max-order: 3
telegram:
  enabled: true
  token: ${BOT_TOKEN:}
  username: ${BOT_NAME:}
api:
  vk:
    group_id: ${GROUP_ID:}
    access_token: ${VK_ACCESS_TOKEN:}
  yandex:
    weather: ${WEATHER_TOKEN:}
    urlGeo: https://geocode-maps.yandex.ru/1.x/
    geo: ${GEO_TOKEN:}
    ip: https://ipv4-internet.yandex.net/api/v0/ip
  cbr: https://www.cbr-xml-daily.ru/latest.js
arango:
  host: localhost
  port: 8529
  user: root
  pass: arango
  db: telega-bot
zeebe:
  client:
    cloud:
      defaultJobWorkerName: novatec-worker