micronaut:
  application:
    name: telegaBot
    default-charset: UTF-8
  server:
    port: 7373
datasources:
  default:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:bot_db}?createDatabaseIfNotExist=true
    driverClassName: org.postgresql.Driver
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'com.malerx'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
liquibase:
  datasource:
    default:
      change-log: classpath\:db/liquibase-changelog.xml
netty:
  default:
    allocator:
      max-order: 3
telegram:
  enabled: true
  token: ${BOT_TOKEN}
  username: ${BOT_NAME}
api:
  yandex:
    weather: ${WEATHER_TOKEN}
    urlGeo: https://geocode-maps.yandex.ru/1.x/
    geo: ${GEO_TOKEN}
    ip: https://ipv4-internet.yandex.net/api/v0/ip