micronaut:
  application:
    name: telegaBot
    default-charset: UTF-8
  server:
    port: 7373
netty:
  default:
    allocator:
      max-order: 3
telegram:
  enabled: true
  token: ${BOT_TOKEN:}
  username: ${BOT_NAME:}
api:
  yandex:
    weather: ${WEATHER_TOKEN:}
    urlGeo: https://geocode-maps.yandex.ru/1.x/
    geo: ${GEO_TOKEN:}
    ip: https://ipv4-internet.yandex.net/api/v0/ip
  cbr: https://www.cbr-xml-daily.ru/latest.js
arango:
  host: ${ARANGO_HOST:localhost}
  port: 8529
  user: root
  pass: ${ARANGO_ROOT_PASSWORD:arango}
  db: telega-bot