package com.malerx.bot.services.weather;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.util.List;

@Data
public class GeoData {
        private String source;
        private String result;
        private String postalCode;
        private String country;
        private String countryIsoCode;
        private String federalDistrict;
        private String regionFiasId;
        private String regionKladrId;
        private String regionIsoCode;
        private String regionWithType;
        private String regionType;
        private String regionTypeFull;
        private String region;
        private String areaFiasId;
        private String areaKladrId;
        private String areaWithType;
        private String areaType;
        private String areaTypeFull;
        private String area;
        private String cityFiasId;
        private String cityKladrId;
        private String cityWithType;
        private String cityType;
        private String cityTypeFull;
        private String city;
        private String cityArea;
        private String cityDistrictFiasId;
        private String cityDistrictKladrId;
        private String cityDistrictWithType;
        private String cityDistrictType;
        private String cityDistrictTypeFull;
        private String cityDistrict;
        private String settlementFiasId;
        private String settlementKladrId;
        private String settlementWithType;
        private String settlementType;
        private String settlementTypeFull;
        private String settlement;
        private String streetFiasId;
        private String streetKladrId;
        private String streetWithType;
        private String streetType;
        private String streetTypeFull;
        private String street;
        private String steadFiasId;
        private String steadKladrId;
        private String steadCadnum;
        private String steadType;
        private String steadTypeFull;
        private String stead;
        private String houseFiasId;
        private String houseKladrId;
        private String houseCadnum;
        private String houseType;
        private String houseTypeFull;
        private String house;
        private String blockType;
        private String blockTypeFull;
        private String block;
        private String entrance;
        private String floor;
        private String flatFiasId;
        private String flatCadnum;
        private String flatType;
        private String flatTypeFull;
        private String flat;
        private String flatArea;
        private String squareMeterPrice;
        private String flatPrice;
        private String postalBox;
        private String fiasId;
        private String fiasCode;
        private String fiasLevel;
        private String fiasActualityState;
        private String kladrId;
        private String capitalMarker;
        private String okato;
        private String oktmo;
        private String taxOffice;
        private String taxOfficeLegal;
        private String timezone;
        @JsonProperty("geo_lat")
        private String geoLat;
        @JsonProperty("geo_lon")
        private String geoLon;
        private String beltwayHit;
        private String beltwayDistance;
        private int qcGeo;
        private int qcComplete;
        private int qcHouse;
        private int qc;
        private String unparsedParts;
        private String metro;
}